# Generated by Django 3.2.8 on 2021-11-08 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='navbar menyu:')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('Aa', 'Aa'), ('Bb', 'Bb'), ('Dd', 'Dd'), ('Ee', 'Ee'), ('Ff', 'Ff'), ('Gg', 'Gg'), ('Hh', 'Hh'), ('Ii', 'Ii'), ('Jj', 'Jj'), ('Kk', 'Kk'), ('Ll', 'Ll'), ('Mm', 'Mm'), ('Nn', 'Nn'), ('Oo', 'Oo'), ('Pp', 'Pp'), ('Qq', 'Qq'), ('Rr', 'Rr'), ('Ss', 'Ss'), ('Tt', 'Tt'), ('Uu', 'Uu'), ('Vv', 'Vv'), ('Xx', 'Xx'), ('Yy', 'Yy'), ('Zz', 'Zz'), ("O'`o'`", "O'`o'`"), ("G'`g'`", "G'`g'`"), ('Shsh', 'Shsh'), ('Chch', 'Chch'), ('Ngng', 'Ngng')], max_length=100, verbose_name='harfni tanlang')),
                ('title', models.CharField(max_length=255, verbose_name='So\n`z ')),
                ('post', models.TextField(verbose_name="So'`zning manosi")),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Rotatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('bilaman', 'bilaman'), ('bilmayman', 'bilmayman')], default='bilmayman', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orthographic_dict.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
